# This is a sample configuration to run a Tripal instance with Docker-Compose.

version: '3'

volumes:
    tripal_sites:
    tripal_private:
    tripal_data:
    tripal_index:

services:

    tripal:
      # image: quay.io/galaxy-genome-annotation/tripal
      build: .
      volumes:
        - "tripal_sites:/var/www/html/sites"
        - "tripal_private:/var/www/private"
      environment:
        UPLOAD_LIMIT: 20M
        MEMORY_LIMIT: 128M
        BASE_URL: https://sunflower.divseekcanada.ca
        BASE_URL_PROTO: https://
        BASE_URL_PATH: /
        DB_HOST: tripal_db
        DB_NAME: tripal
      ports:
        - "8200:80"
      depends_on:
        - tripal_db
        - elasticsearch

    tripal_db:
      image: quay.io/galaxy-genome-annotation/chado:latest
      environment:
        - POSTGRES_PASSWORD=postgres
          # The default chado image would try to install the schema on first run,
          # we just want the tools to be available.
        - INSTALL_CHADO_SCHEMA=0
        - INSTALL_YEAST_DATA=0
        - PGDATA=/var/lib/postgresql/data/
      volumes:
        - "tripal_data:/var/lib/postgresql/data/"

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
      environment:
        TAKE_FILE_OWNERSHIP: "true"
      volumes:
        - "tripal_index:/usr/share/elasticsearch/data"

